x86_docker_builder:
  env:
    GITHUB_TOKEN: ENCRYPTED[b9fc840abb3acc8b67824de3e20417357c6b83eaa2088d8c8a6ef90ad20a74b36614c353eb082ce695e2d07a509e2c09]
  build_script: docker build -t ghcr.io/cheriot-platform/sail:x86_64-latest .
  login_script: |
    if [  "$CIRRUS_BRANCH" == 'main' ] ; then echo $GITHUB_TOKEN | docker login ghcr.io -u davidchisnall --password-stdin ; fi
  push_script: |
    if [  "$CIRRUS_BRANCH" == 'main' ] ; then docker push ghcr.io/cheriot-platform/sail:x86_64-latest ; fi

arm_docker_builder:
  env:
    CIRRUS_ARCH: arm64
    GITHUB_TOKEN: ENCRYPTED[b9fc840abb3acc8b67824de3e20417357c6b83eaa2088d8c8a6ef90ad20a74b36614c353eb082ce695e2d07a509e2c09]
  build_script: docker build -t ghcr.io/cheriot-platform/sail:aarch64-latest .
  login_script: |
    if [  "$CIRRUS_BRANCH" == 'main' ] ; then echo $GITHUB_TOKEN | docker login ghcr.io -u davidchisnall --password-stdin ; fi
  push_script: |
    if [  "$CIRRUS_BRANCH" == 'main' ] ; then docker push ghcr.io/cheriot-platform/sail:aarch64-latest ; fi

final_docker_builder:
  only_if: $CIRRUS_BRANCH == "main"
  env:
    GITHUB_TOKEN: ENCRYPTED[b9fc840abb3acc8b67824de3e20417357c6b83eaa2088d8c8a6ef90ad20a74b36614c353eb082ce695e2d07a509e2c09]
  depends_on:
    - x86
    - arm
  login_script: echo $GITHUB_TOKEN | docker login ghcr.io -u davidchisnall --password-stdin
  manifest_script:
    - docker manifest create ghcr.io/cheriot-platform/sail:latest --amend ghcr.io/cheriot-platform/sail:x86_64-latest --amend ghcr.io/cheriot-platform/sail:aarch64-latest
    - docker manifest push --purge ghcr.io/cheriot-platform/sail:latest
